import type { NewDisciplineRow } from '../schema/disciplines.js';

/**
 * NID disciplines seeded for the prototype.
 * Source: NID's public programmes catalog at https://www.nid.edu/academics/programmes
 * accent_token_name maps to the discipline-color theming in semantic.css.
 */
export const seedDisciplines: NewDisciplineRow[] = [
  // Bachelor of Design (B.Des) — Ahmedabad only
  {
    id: 'disc_industrial_design',
    slug: 'industrial-design',
    name: 'Industrial Design',
    descriptionMd:
      'Form, function, and manufacturability for everyday products, durables, and industrial equipment. Graduates work in product strategy, hardware design, and design engineering.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'bachelors',
    accentTokenName: 'navy',
    version: 1,
    active: true,
  },
  {
    id: 'disc_communication_design',
    slug: 'communication-design',
    name: 'Communication Design',
    descriptionMd:
      'Visual systems, typography, brand, editorial, and motion graphics. Strong fit for roles around print, digital, brand design, and content design.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'bachelors',
    accentTokenName: 'red',
    version: 1,
    active: true,
  },
  {
    id: 'disc_textile_design',
    slug: 'textile-design',
    name: 'Textile Design',
    descriptionMd:
      'Fabric, surface, and material design across apparel, home, and industrial textiles. Graduates work on weaves, prints, finishes, and trend forecasting.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'both',
    accentTokenName: 'purple',
    version: 1,
    active: true,
  },

  // Master of Design (M.Des) — 3 campuses
  {
    id: 'disc_animation_film',
    slug: 'animation-film-design',
    name: 'Animation Film Design',
    descriptionMd:
      '2D, 3D, and stop-motion animation for film, advertising, and interactive media. Storyboarding, character design, motion design.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'yellow',
    version: 1,
    active: true,
  },
  {
    id: 'disc_apparel_design',
    slug: 'apparel-design',
    name: 'Apparel Design',
    descriptionMd: 'Fashion, garment construction, pattern-making, and ready-to-wear collections.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'purple',
    version: 1,
    active: true,
  },
  {
    id: 'disc_ceramic_glass',
    slug: 'ceramic-glass-design',
    name: 'Ceramic and Glass Design',
    descriptionMd: 'Form, glaze, and material exploration in ceramics and glass for objects and architecture.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'green',
    version: 1,
    active: true,
  },
  {
    id: 'disc_film_video',
    slug: 'film-video-communication',
    name: 'Film and Video Communication',
    descriptionMd: 'Documentary, narrative, and experimental film for screen, advertising, and editorial.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'yellow',
    version: 1,
    active: true,
  },
  {
    id: 'disc_furniture_interior',
    slug: 'furniture-interior-design',
    name: 'Furniture and Interior Design',
    descriptionMd: 'Spatial design, furniture, and interior product design across residential and commercial contexts.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'green',
    version: 1,
    active: true,
  },
  {
    id: 'disc_graphic_design',
    slug: 'graphic-design',
    name: 'Graphic Design',
    descriptionMd: 'Print, identity, editorial, and brand systems. Strong fit for visual designer and brand roles.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'red',
    version: 1,
    active: true,
  },
  {
    id: 'disc_information_design',
    slug: 'information-design',
    name: 'Information Design',
    descriptionMd: 'Data visualization, infographics, wayfinding, and complex-information clarity.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad', 'campus_bengaluru']),
    programme: 'masters',
    accentTokenName: 'cyan',
    version: 1,
    active: true,
  },
  {
    id: 'disc_interaction_design',
    slug: 'interaction-design',
    name: 'Interaction Design',
    descriptionMd:
      'UX research, interaction patterns, prototyping, and human-centered systems for software and connected devices.',
    campusIdsJson: JSON.stringify(['campus_bengaluru']),
    programme: 'masters',
    accentTokenName: 'cyan',
    version: 1,
    active: true,
  },
  {
    id: 'disc_lifestyle_accessory',
    slug: 'lifestyle-accessory-design',
    name: 'Lifestyle and Accessory Design',
    descriptionMd: 'Accessories, jewellery, and lifestyle objects across leather, metal, and craft material.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'purple',
    version: 1,
    active: true,
  },
  {
    id: 'disc_new_media',
    slug: 'new-media-design',
    name: 'New Media Design',
    descriptionMd: 'Interactive installations, generative design, and emerging-media practice.',
    campusIdsJson: JSON.stringify(['campus_bengaluru']),
    programme: 'masters',
    accentTokenName: 'cyan',
    version: 1,
    active: true,
  },
  {
    id: 'disc_photography_design',
    slug: 'photography-design',
    name: 'Photography Design',
    descriptionMd: 'Documentary, editorial, and commercial photography practice.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'yellow',
    version: 1,
    active: true,
  },
  {
    id: 'disc_product_design',
    slug: 'product-design',
    name: 'Product Design',
    descriptionMd: 'Industrial product, hardware, and design-engineering for consumer and B2B products.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad', 'campus_gandhinagar']),
    programme: 'masters',
    accentTokenName: 'navy',
    version: 1,
    active: true,
  },
  {
    id: 'disc_strategic_design',
    slug: 'strategic-design-management',
    name: 'Strategic Design Management',
    descriptionMd: 'Design strategy, organisational design, and business-aligned design leadership.',
    campusIdsJson: JSON.stringify(['campus_gandhinagar']),
    programme: 'masters',
    accentTokenName: 'navy',
    version: 1,
    active: true,
  },
  {
    id: 'disc_toy_game',
    slug: 'toy-game-design',
    name: 'Toy and Game Design',
    descriptionMd: 'Physical and digital game design, toy systems, and play-based learning.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'yellow',
    version: 1,
    active: true,
  },
  {
    id: 'disc_transportation',
    slug: 'transportation-automobile-design',
    name: 'Transportation and Automobile Design',
    descriptionMd: 'Vehicle styling, automotive engineering, and transportation systems design.',
    campusIdsJson: JSON.stringify(['campus_ahmedabad']),
    programme: 'masters',
    accentTokenName: 'navy',
    version: 1,
    active: true,
  },
  {
    id: 'disc_universal_design',
    slug: 'universal-design',
    name: 'Universal Design',
    descriptionMd: 'Inclusive design, accessibility, and design for diverse abilities and contexts.',
    campusIdsJson: JSON.stringify(['campus_bengaluru']),
    programme: 'masters',
    accentTokenName: 'cyan',
    version: 1,
    active: true,
  },
  {
    id: 'disc_digital_game',
    slug: 'digital-game-design',
    name: 'Digital Game Design',
    descriptionMd: 'Video-game design, narrative systems, and interactive entertainment.',
    campusIdsJson: JSON.stringify(['campus_bengaluru']),
    programme: 'masters',
    accentTokenName: 'cyan',
    version: 1,
    active: true,
  },
];
